[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Enable form detection
[forms]
  enabled = true

# Configure form redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/*"
  status = 200

# Handle static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form success redirect
[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
