[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyAZkP4EynfssAMT4-mdOoTWXifgWz7zxC4"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "jcpapp-18205.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "jcpapp-18205"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "jcpapp-18205.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "230450676718"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:230450676718:web:ecb1e7ae68e3dad41cc4ff"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-5CZ91ZSRNW"
  NEXT_PUBLIC_DATABASE_URL = "https://jcpapp-18205-default-rtdb.firebaseio.com/"
  NEXT_PUBLIC_ADMIN_EMAIL = "admin@jcp.com"
  NEXT_PUBLIC_ADMIN_PASSWORD = "admin123"

# Headers de seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers para assets est치ticos
[[headers]]
  for = "/Assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para datos JSON
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=86400"

# Headers para p치ginas HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

# Headers para archivos CSS y JS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para im치genes
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para fuentes
[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirecciones
[[redirects]]
  from = "/catalog"
  to = "/catalog/"
  status = 301

[[redirects]]
  from = "/amasadoras-industriales"
  to = "/amasadoras-industriales/"
  status = 301

[[redirects]]
  from = "/hornos-industriales"
  to = "/hornos-industriales/"
  status = 301

[[redirects]]
  from = "/combos-soluciones"
  to = "/combos-soluciones/"
  status = 301

[[redirects]]
  from = "/repuestos"
  to = "/repuestos/"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/maquinaria"
  to = "/maquinaria/"
  status = 301

# SPA fallback para rutas din치micas
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200