[build]
  publish = "out"
  command = "npm run build:netlify"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

# Mobile-first performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Mobile performance optimizations
    Vary = "Accept-Encoding, User-Agent"
    Accept-Encoding = "gzip, deflate, br"

[[headers]]
  for = "/Assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Mobile image optimization
    Accept-Ranges = "bytes"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Mobile JavaScript optimization
    Content-Encoding = "gzip"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    # Mobile CSS optimization
    Content-Encoding = "gzip"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

# Mobile-specific optimizations
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"

[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/avif"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Mobile performance redirects
[[redirects]]
  from = "/mobile/*"
  to = "/index.html"
  status = 200
  conditions = {User_Agent = "Mobile"}
